service: epicollect-migrator

provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  timeout: 300

functions:
  migrate:
    handler: epicollect_migrator.handler.handle
    name: epicollect_migrator
    events:
      - schedule: rate(24 hours)
    environment:
      EPICOLLECT_BASE_URL: ${file(./serverless.env.yml):${self:provider.stage}.EPICOLLECT_BASE_URL}
      EPICOLLECT_PROJECT_NAME: ${file(./serverless.env.yml):${self:provider.stage}.EPICOLLECT_PROJECT_NAME}
      EPICOLLECT_PROJECT_NAME_2: ${file(./serverless.env.yml):${self:provider.stage}.EPICOLLECT_PROJECT_NAME_2}
      DATABASE_CONNECTION_URI: ${file(./serverless.env.yml):${self:provider.stage}.DATABASE_CONNECTION_URI}

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
