service: epicollect-migrator

provider:
  name: aws
  region: us-west-2
  runtime: python3.7

functions:
  migrate:
    handler: epicollect_migrator.handler.handle
    name: epicollect_migrator
    events:
      - schedule: rate(24 hours)
    environment:
      EPICOLLECT_BASE_URL: ${env:EPICOLLECT_BASE_URL, ssm:EPICOLLECT_BASE_URL}
      EPICOLLECT_PROJECT_NAME: ${env:EPICOLLECT_PROJECT_NAME, ssm:EPICOLLECT_PROJECT_NAME}
      EPICOLLECT_PROJECT_NAME_2: ${env:EPICOLLECT_PROJECT_NAME_2, ssm:EPICOLLECT_PROJECT_NAME_2}
      DATABASE_CONNECTION_URI: ${env:DATABASE_CONNECTION_URI, ssm:DATABASE_CONNECTION_URI~true}

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
