version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.7
    commands:
      - npm install -g serverless
      - sls plugin install -n serverless-python-requirements
  build:
    commands:
      - sls deploy


